"""clean_slate

Revision ID: 249b525d118d
Revises: 
Create Date: 2026-05-10 14:20:18.214855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249b525d118d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('is_buyer_maker', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agg_trades_market_type'), 'agg_trades', ['market_type'], unique=False)
    op.create_index(op.f('ix_agg_trades_symbol'), 'agg_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_agg_trades_time'), 'agg_trades', ['time'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('exchange_accounts',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('is_paper', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'market_type', 'time', name='uq_funding_rate')
    )
    op.create_index(op.f('ix_funding_rates_symbol'), 'funding_rates', ['symbol'], unique=False)
    op.create_index(op.f('ix_funding_rates_time'), 'funding_rates', ['time'], unique=False)
    op.create_table('liquidations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidations_symbol'), 'liquidations', ['symbol'], unique=False)
    op.create_index(op.f('ix_liquidations_time'), 'liquidations', ['time'], unique=False)
    op.create_table('mark_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('index_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'market_type', 'time', name='uq_mark_price')
    )
    op.create_index(op.f('ix_mark_prices_symbol'), 'mark_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_mark_prices_time'), 'mark_prices', ['time'], unique=False)
    op.create_table('open_interest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('oi_contracts', sa.Float(), nullable=False),
    sa.Column('oi_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'market_type', 'time', name='uq_open_interest')
    )
    op.create_index(op.f('ix_open_interest_symbol'), 'open_interest', ['symbol'], unique=False)
    op.create_index(op.f('ix_open_interest_time'), 'open_interest', ['time'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_strategy_id'), 'positions', ['strategy_id'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strategy_class', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('parameters_schema', sa.JSON(), nullable=True),
    sa.Column('signal_definitions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'market_type', 'time', name='uq_tick')
    )
    op.create_index(op.f('ix_ticks_market_type'), 'ticks', ['market_type'], unique=False)
    op.create_index(op.f('ix_ticks_symbol'), 'ticks', ['symbol'], unique=False)
    op.create_index(op.f('ix_ticks_time'), 'ticks', ['time'], unique=False)
    op.create_table('watched_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeframes', sa.JSON(), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=True),
    sa.Column('quote_asset', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'market_type', name='uq_watched_asset')
    )
    op.create_index(op.f('ix_watched_assets_symbol'), 'watched_assets', ['symbol'], unique=False)
    op.create_table('strategy_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('leg_num', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('tick_process', sa.Boolean(), nullable=False),
    sa.Column('subscribe_depth', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_asset', sa.String(length=20), nullable=True),
    sa.Column('quote_asset', sa.String(length=20), nullable=True),
    sa.Column('exchange_account_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_assets_strategy_id'), 'strategy_assets', ['strategy_id'], unique=False)
    op.create_table('strategy_exchange_refs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('exchange_account_id', sa.String(), nullable=False),
    sa.Column('exchange_num', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'exchange_num', name='uq_strategy_exchange_num')
    )
    op.create_index(op.f('ix_strategy_exchange_refs_strategy_id'), 'strategy_exchange_refs', ['strategy_id'], unique=False)
    op.create_table('trade_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_type', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=False),
    sa.Column('quote_asset', sa.String(length=20), nullable=False),
    sa.Column('bought_asset', sa.String(length=20), nullable=False),
    sa.Column('sold_asset', sa.String(length=20), nullable=False),
    sa.Column('bought_qty', sa.Float(), nullable=False),
    sa.Column('sold_qty', sa.Float(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('fee_asset', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_history_occurred_at'), 'trade_history', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_trade_history_strategy_id'), 'trade_history', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trade_history_symbol'), 'trade_history', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_history_symbol'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_strategy_id'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_occurred_at'), table_name='trade_history')
    op.drop_table('trade_history')
    op.drop_index(op.f('ix_strategy_exchange_refs_strategy_id'), table_name='strategy_exchange_refs')
    op.drop_table('strategy_exchange_refs')
    op.drop_index(op.f('ix_strategy_assets_strategy_id'), table_name='strategy_assets')
    op.drop_table('strategy_assets')
    op.drop_index(op.f('ix_watched_assets_symbol'), table_name='watched_assets')
    op.drop_table('watched_assets')
    op.drop_index(op.f('ix_ticks_time'), table_name='ticks')
    op.drop_index(op.f('ix_ticks_symbol'), table_name='ticks')
    op.drop_index(op.f('ix_ticks_market_type'), table_name='ticks')
    op.drop_table('ticks')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_positions_strategy_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_open_interest_time'), table_name='open_interest')
    op.drop_index(op.f('ix_open_interest_symbol'), table_name='open_interest')
    op.drop_table('open_interest')
    op.drop_index(op.f('ix_mark_prices_time'), table_name='mark_prices')
    op.drop_index(op.f('ix_mark_prices_symbol'), table_name='mark_prices')
    op.drop_table('mark_prices')
    op.drop_index(op.f('ix_liquidations_time'), table_name='liquidations')
    op.drop_index(op.f('ix_liquidations_symbol'), table_name='liquidations')
    op.drop_table('liquidations')
    op.drop_index(op.f('ix_funding_rates_time'), table_name='funding_rates')
    op.drop_index(op.f('ix_funding_rates_symbol'), table_name='funding_rates')
    op.drop_table('funding_rates')
    op.drop_table('exchange_accounts')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_agg_trades_time'), table_name='agg_trades')
    op.drop_index(op.f('ix_agg_trades_symbol'), table_name='agg_trades')
    op.drop_index(op.f('ix_agg_trades_market_type'), table_name='agg_trades')
    op.drop_table('agg_trades')
    # ### end Alembic commands ###
